### ISSUE TITLE
how to use this code step by step

### ISSUE THREAD

**Issue by b4go3s** [YHJRUBEN/SimpleFunctionSR#1]
dear
can you share how to use this code step by step

**Comment by YHJRUBEN** [comment]
You can run `runSFTest.m` directly to start training and testing. 
Please uncomment line 24 and 25 if you would like to train new regressors.
Check `./SF` dir for function details used in training.

**Comment by b4go3s** [comment]
i've had try but error "Index exceeds matrix dimensions"
error in runSFTest (line 37)
show_idx = show_idx(1 : 3);

**Comment by YHJRUBEN** [comment]
You might miss the test image dir `'../Set14/'`. Check the dir structure or change as you like. Refer to line 3 to 13.
